import 'package:equatable/equatable.dart';

// ApiFailure and ApiException now live in core/network/api_failure.dart,
// which is the union of both apps' vocabularies. Re-exported here so
// existing importers of this repository keep seeing them.
export '../../../../core/network/api_failure.dart';

import '../../../../core/models/journey.dart';
import '../../../../core/models/journey_plan.dart';
import '../../../../core/models/ticket.dart';
import '../../../../core/money.dart';

/// Contract for everything the passenger app needs from the backend.
///
/// An interface rather than a concrete Dio client so screens and controllers can
/// be tested against a fake, with no network and no mocking framework. It also
/// keeps the "what can this app do" question answerable in one place.
abstract interface class TransportRepository {
  /// Stops matching [query], by name, Amharic name or code.
  ///
  /// An empty or whitespace-only [query] is a *browse*, not a search that
  /// matches nothing: it returns a default page of stops. The picker calls this
  /// with no query when it opens, so returning empty for a blank query renders
  /// an empty box on a server that has plenty to offer.
  Future<List<Place>> searchPlaces(String query);

  /// Stops nearest [point], closest first, each with its real distance.
  ///
  /// The ranking is done by the server, not here. [searchPlaces] returns a
  /// bounded, name-ordered page, so ranking that page locally would pick the
  /// stop that happens to sort near "A" rather than the one the passenger is
  /// standing at — a confidently wrong answer.
  Future<List<NearbyStop>> nearbyStops(GeoPoint point);

  Future<JourneyPlan> planJourney(JourneyPlanRequest request);

  /// Starts a payment. [idempotencyKey] must be generated by the caller BEFORE
  /// the first attempt and reused on retries (I2).
  Future<PaymentStartResult> startPayment({
    required Money amount,
    required PaymentMethod method,
    required String idempotencyKey,
    String? journeyId,
  });

  /// Re-reads payment status. Used after a provider redirect returns.
  Future<PaymentStatus> paymentStatus(String paymentId);

  /// Fetches the ticket issued against a confirmed payment.
  ///
  /// Returns null while the ticket has not been issued yet — which is a normal
  /// intermediate state, not an error. The caller polls until it is non-null.
  Future<IssuedTicket?> ticketForPayment(String paymentId);

  Future<List<IssuedTicket>> myTickets();

  /// Planned journeys, newest first. Distinct from [myTickets]: most searches
  /// are never bought, and hiding them would lose the trip the passenger just
  /// planned.
  ///
  /// The result carries whether the caller was signed in, so a signed-out
  /// visitor gets "sign in to see your trips" rather than an empty list that
  /// looks like they have none.
  Future<TripsResult> myTrips();
}

/// Outcome of a trip-history request.
class TripsResult {
  const TripsResult({required this.trips, required this.signedIn});

  final List<PastTrip> trips;
  final bool signedIn;
}

/// A stop near the passenger's position, with the distance to it.
class NearbyStop extends Equatable {
  const NearbyStop({required this.place, required this.distanceMeters});

  final Place place;
  final int distanceMeters;

  /// "45 m" / "1.4 km" — the unit a pedestrian cares about.
  ///
  /// Metres rather than "minutes away": the app has no pedestrian routing, so a
  /// distance the passenger can check against what they can see is more honest
  /// than an estimate they cannot.
  String get displayDistance {
    if (distanceMeters < 1000) return '$distanceMeters m';
    return '${(distanceMeters / 1000).toStringAsFixed(1)} km';
  }

  @override
  List<Object?> get props => [place, distanceMeters];
}

/// A journey the passenger planned, whether or not they bought it.
class PastTrip extends Equatable {
  const PastTrip({
    required this.id,
    required this.originLabel,
    required this.destinationLabel,
    required this.totalFare,
    required this.durationSeconds,
    required this.transferCount,
    required this.departureTime,
    this.ticketReference,
  });

  final String id;
  final String originLabel;
  final String destinationLabel;
  final Money totalFare;
  final int durationSeconds;
  final int transferCount;
  final DateTime departureTime;

  /// Set only when a ticket was actually issued for this journey.
  final String? ticketReference;

  bool get wasTravelled => ticketReference != null;

  String get durationLabel {
    final minutes = (durationSeconds / 60).round();
    if (minutes < 60) return '$minutes min';
    return '${minutes ~/ 60} h ${(minutes % 60).toString().padLeft(2, '0')}';
  }

  static PastTrip fromJson(Map<String, dynamic> json) => PastTrip(
        id: json['id'] as String? ?? '',
        originLabel: json['originLabel'] as String? ?? '—',
        destinationLabel: json['destinationLabel'] as String? ?? '—',
        totalFare: Money(json['totalFareFils'] as int? ?? 0),
        durationSeconds: json['totalDurationSeconds'] as int? ?? 0,
        transferCount: json['transferCount'] as int? ?? 0,
        departureTime:
            DateTime.tryParse(json['departureTime'] as String? ?? '')?.toLocal() ??
                DateTime.now(),
        ticketReference: json['ticketReference'] as String?,
      );

  @override
  List<Object?> get props =>
      [id, originLabel, destinationLabel, totalFare, ticketReference];
}

/// A minimal fare quote returned by the backend before payment.
///
/// Separate from the journey's `totalFare`: the quote is what the passenger is
/// shown to authorise, and it is what the payment is created against. Keeping
/// them distinct is what allows the server to detect price drift between
/// planning and purchase.
class FareQuote extends Equatable {
  const FareQuote({
    required this.token,
    required this.fare,
    required this.expiresAt,
    this.ruleKey,
    this.ruleVersion,
  });

  final String token;
  final Money fare;
  final DateTime expiresAt;

  /// The pinned fare rule version (I3). Recorded on the ticket so the charge
  /// remains explicable after fare policy changes.
  final String? ruleKey;
  final int? ruleVersion;

  bool isExpiredAt(DateTime now) => now.isAfter(expiresAt);

  static FareQuote fromJson(Map<String, dynamic> json) {
    return FareQuote(
      token: json['quoteToken'] as String? ?? '',
      fare: Money(json['totalFareFils'] as int? ?? 0),
      expiresAt:
          DateTime.tryParse(json['expiresAt'] as String? ?? '')?.toLocal() ??
              DateTime.now(),
      ruleKey: json['ruleKey'] as String?,
      ruleVersion: json['ruleVersion'] as int?,
    );
  }

  @override
  List<Object?> get props => [token, fare, expiresAt, ruleKey, ruleVersion];
}
