/**
 * Payment orchestrator.
 *
 * Sits between callers (ticketing, cash/agent flows) and provider adapters.
 * Its job is to make the two invariants that matter impossible to bypass:
 *
 *   I2 — every create carries an idempotency key, and repeats return the
 *        original payment rather than charging again.
 *   I1 — nothing here can issue a ticket. The orchestrator's only outputs are
 *        payment state. Ticket issuance is a separate module that must observe
 *        a CONFIRMED payment, so there is no path from "user tapped Pay" to
 *        "valid ticket".
 *
 * The persistence boundary is deliberately narrow (a small repository interface
 * rather than Prisma directly) so the orchestration logic is testable without a
 * database, while the Prisma implementation supplies the real unique-constraint
 * behaviour.
 */

import {
  ProviderRegistry,
  PaymentMethodCode,
  PaymentProviderError,
  PaymentStatusCode,
} from './payment-provider';

export type PaymentRecordStatus = PaymentStatusCode;

export interface PaymentRecord {
  id: string;
  reference: string;
  userId: string;
  idempotencyKey: string;
  amountFils: number;
  currency: string;
  method: PaymentMethodCode;
  status: PaymentRecordStatus;
  providerReference: string | null;
  fareCalculationId: string | null;
  vehicleId: string | null;
  tripId: string | null;
  quantity: number | null;
  collectedByStaffId: string | null;
  shiftId: string | null;
}

/**
 * Persistence contract. The Prisma implementation must rely on the unique index
 * on `idempotencyKey` to make `create` effectively atomic.
 */
export interface PaymentRepository {
  findByIdempotencyKey(key: string): Promise<PaymentRecord | null>;
  findById(id: string): Promise<PaymentRecord | null>;
  create(input: NewPaymentRecord): Promise<PaymentRecord>;
  updateStatus(
    id: string,
    status: PaymentRecordStatus,
    extra?: Partial<PaymentRecord>,
  ): Promise<PaymentRecord>;
}

export interface NewPaymentRecord {
  reference: string;
  userId: string;
  idempotencyKey: string;
  amountFils: number;
  currency: string;
  method: PaymentMethodCode;
  status: PaymentRecordStatus;
  fareCalculationId?: string | null;
  vehicleId?: string | null;
  tripId?: string | null;
  quantity?: number | null;
  collectedByStaffId?: string | null;
  shiftId?: string | null;
  providerReference?: string | null;
}

export interface CreatePaymentInput {
  userId: string;
  amountFils: number;
  currency: string;
  method: PaymentMethodCode;
  /** REQUIRED. Generated by the caller before the first attempt. */
  idempotencyKey: string;
  fareCalculationId?: string | null;
  vehicleId?: string | null;
  tripId?: string | null;
  quantity?: number | null;
  collectedByStaffId?: string | null;
  shiftId?: string | null;
  payerPhone?: string;
  description?: string;
}

export interface CreatePaymentResult {
  payment: PaymentRecord;
  /** True when an existing payment was returned for a repeated key. */
  idempotentReplay: boolean;
  redirectUrl?: string | null;
}

/** Payment states that must never change again. */
export function isTerminalStatus(status: PaymentStatusCode): boolean {
  return (
    status === 'CONFIRMED' ||
    status === 'FAILED' ||
    status === 'TIMEOUT' ||
    status === 'REVERSED' ||
    status === 'REFUNDED' ||
    status === 'PARTIALLY_REFUNDED'
  );
}

function defaultReference(): string {
  const rand = Math.random().toString(36).slice(2, 8).toUpperCase();
  return `PAY-${Date.now().toString(36).toUpperCase()}-${rand}`;
}

/**
 * Recognises a unique-constraint violation from either source:
 *  - Prisma's `P2002` at runtime
 *  - a `DuplicateKeyError` from the in-memory repository in tests
 *
 * Both mean the same thing: another request already claimed this key.
 * Checked structurally by `name` so this module has no dependency on the
 * test double or on a concrete Prisma import.
 */
export function isUniqueViolation(error: unknown): boolean {
  if (!error || typeof error !== 'object') return false;
  const e = error as { name?: string; code?: unknown };
  return e.name === 'DuplicateKeyError' || e.code === 'P2002';
}

export class PaymentOrchestratorService {
  constructor(
    private readonly repo: PaymentRepository,
    private readonly registry: ProviderRegistry,
    private readonly referenceFactory: () => string = defaultReference,
  ) {}

  /**
   * Creates a payment, or returns the existing one for this idempotency key.
   *
   * The duplicate check is an optimisation, not the guarantee. Between the check
   * and the insert, a concurrent request can win the race — the database unique
   * index then rejects our insert. That rejection is caught and the winning
   * payment is returned, so parallel double-taps converge on one charge instead
   * of surfacing an error to the passenger.
   */
  async createPayment(input: CreatePaymentInput): Promise<CreatePaymentResult> {
    if (!input.idempotencyKey || input.idempotencyKey.length < 8) {
      throw new Error('idempotencyKey is required and must be non-trivial');
    }
    if (!Number.isInteger(input.amountFils) || input.amountFils <= 0) {
      throw new Error(`Payment amount must be a positive integer, got ${input.amountFils}`);
    }

    const existing = await this.repo.findByIdempotencyKey(input.idempotencyKey);
    if (existing) {
      return { payment: existing, idempotentReplay: true };
    }

    try {
      const payment = await this.repo.create({
        reference: this.referenceFactory(),
        userId: input.userId,
        idempotencyKey: input.idempotencyKey,
        amountFils: input.amountFils,
        currency: input.currency,
        method: input.method,
        status: 'CREATED',
        fareCalculationId: input.fareCalculationId ?? null,
        collectedByStaffId: input.collectedByStaffId ?? null,
        shiftId: input.shiftId ?? null,
        providerReference: this.referenceFactory(),
      });
      return { payment, idempotentReplay: false };
    } catch (error) {
      // Lost the race: another request inserted this key first. Return theirs.
      if (isUniqueViolation(error)) {
        const winner = await this.repo.findByIdempotencyKey(input.idempotencyKey);
        if (winner) return { payment: winner, idempotentReplay: true };
      }
      throw error;
    }
  }

  /**
   * Starts the payment at the provider.
   *
   * Returns whatever state the provider reported. Callers must NOT treat a
   * redirect URL as proof of payment — only CONFIRMED is, and only that state
   * unlocks ticket issuance.
   */
  async initiate(
    paymentId: string,
    idempotencyKey: string,
    args: { payerPhone: string; description: string; returnUrl?: string | null },
  ): Promise<CreatePaymentResult> {
    const payment = await this.repo.findById(paymentId);
    if (!payment) throw new Error(`Payment ${paymentId} not found`);

    // Already terminal: never re-initiate, a replay must not reopen a closed payment.
    if (isTerminalStatus(payment.status)) {
      return { payment, idempotentReplay: true };
    }

    const adapter = this.registry.get(payment.method);
    const providerReference = payment.providerReference ?? this.referenceFactory();

    try {
      const result = await adapter.initiate(
        {
          providerReference,
          amountFils: payment.amountFils,
          currency: payment.currency,
          payerPhone: args.payerPhone,
          description: args.description,
          returnUrl: args.returnUrl ?? null,
        },
        idempotencyKey,
      );

      const updated = await this.repo.updateStatus(payment.id, result.status, {
        providerReference: result.providerReference,
      });

      return {
        payment: updated,
        idempotentReplay: false,
        redirectUrl: result.redirectUrl ?? null,
      };
    } catch (error) {
      // A provider that throws must not leave the payment dangling in CREATED.
      if (error instanceof PaymentProviderError) {
        const failed = await this.repo.updateStatus(payment.id, 'FAILED');
        return { payment: failed, idempotentReplay: false };
      }
      throw error;
    }
  }

  /**
   * Authorises and captures, confirming funds.
   *
   * Capture implies initiation: a caller that reaches capture without a prior
   * initiate still gets a correct result, rather than an opaque provider error.
   */
  async capture(paymentId: string, idempotencyKey: string): Promise<PaymentRecord> {
    const payment = await this.repo.findById(paymentId);
    if (!payment) throw new Error(`Payment ${paymentId} not found`);
    if (payment.status === 'CONFIRMED') return payment; // I2 replay
    if (isTerminalStatus(payment.status)) return payment;

    const adapter = this.registry.get(payment.method);
    const providerReference = payment.providerReference ?? this.referenceFactory();

    // Providers have no record until initiate has run. Authorise first.
    await adapter.initiate(
      {
        providerReference,
        amountFils: payment.amountFils,
        currency: payment.currency,
        payerPhone: '',
        description: '',
        returnUrl: null,
      },
      idempotencyKey,
    );

    const result = await adapter.capture({
      providerReference,
      providerHandle: null,
      amountFils: payment.amountFils,
      idempotencyKey,
    });

    return this.repo.updateStatus(payment.id, result.status);
  }

  /** Re-reads provider state. Used by webhook reconciliation and polling. */
  async refreshStatus(paymentId: string): Promise<PaymentRecord> {
    const payment = await this.repo.findById(paymentId);
    if (!payment) throw new Error(`Payment ${paymentId} not found`);
    if (isTerminalStatus(payment.status)) return payment;

    const adapter = this.registry.get(payment.method);
    if (!adapter.supportsPolling) return payment;

    const result = await adapter.status(payment.providerReference ?? '');
    return this.repo.updateStatus(payment.id, result.status);
  }

  async refund(
    paymentId: string,
    idempotencyKey: string,
    amountFils: number,
    reason: string,
  ): Promise<PaymentRecord> {
    const payment = await this.repo.findById(paymentId);
    if (!payment) throw new Error(`Payment ${paymentId} not found`);
    if (payment.status === 'REFUNDED') return payment; // I2 replay

    if (payment.status !== 'CONFIRMED') {
      throw new Error(`Cannot refund a payment in state ${payment.status}`);
    }
    if (!Number.isInteger(amountFils) || amountFils <= 0 || amountFils > payment.amountFils) {
      throw new Error(`Invalid refund amount ${amountFils}`);
    }

    const adapter = this.registry.get(payment.method);
    const result = await adapter.refund({
      providerReference: payment.providerReference ?? '',
      providerHandle: null,
      amountFils,
      reason,
      idempotencyKey,
    });

    return this.repo.updateStatus(payment.id, result.status);
  }

  /**
   * Applies a provider webhook result.
   *
   * Webhooks arrive late, duplicated, and out of order. A settled payment is
   * never disturbed, so a stale retry cannot undo a completed payment.
   */
  async applyWebhookResult(
    paymentId: string,
    reportedStatus: PaymentStatusCode,
  ): Promise<PaymentRecord> {
    const payment = await this.repo.findById(paymentId);
    if (!payment) throw new Error(`Payment ${paymentId} not found`);

    if (isTerminalStatus(payment.status)) return payment; // ignore stale webhooks

    // Intermediate states are not authoritative; wait for a terminal webhook.
    if (reportedStatus !== 'CONFIRMED' && reportedStatus !== 'FAILED') {
      return payment;
    }

    return this.repo.updateStatus(payment.id, reportedStatus);
  }
}
