import '../../../../core/models/journey.dart';
import '../../../../core/models/ticket.dart';
import '../../../../core/models/ticket_validation.dart';
import '../../../../core/models/vehicle.dart';
import '../../../../core/money.dart';
import '../../journey_planner/domain/transport_repository.dart';

/// What the vehicle-code flow needs from the backend.
///
/// Separate from `TransportRepository` because it is a genuinely different
/// purchase: the journey flow buys a *planned itinerary*, this one buys
/// *boarding a specific vehicle right now*. Folding it in would mean either a
/// nullable `journeyId` on every payment call — which reintroduces exactly the
/// "which of these two is it?" ambiguity the repository doc warns about — or a
/// second repository anyway.
///
/// Reuses [ApiFailure] and [ApiException] from the journey repository rather than
/// redeclaring them, so a single `switch` covers every failure the UI can hit,
/// whichever flow produced it.
abstract interface class VehicleRepository {
  /// Steps 2–3: looks up a vehicle by its code.
  ///
  /// [boardingPoint] is the passenger's resolved position, when one is
  /// available. It is a *request for a quote*, not a claim: the server decides
  /// which stop the passenger is at, how far it is, and what that costs. The
  /// client deliberately does no pricing of its own — see the note on
  /// [VehicleProfile.fare]. Supplying null is legal and means "quote the flat
  /// fare"; the flow must still work when permission is denied.
  ///
  /// Returns **null** when no vehicle is registered under that code. This is a
  /// legitimate answer, not an error, and is deliberately not an exception: the
  /// caller shows "Vehicle Not Found" and stops, which is different handling
  /// from a failure and must not share a code path with it.
  ///
  /// Throws [ApiException] only when there is no answer at all — network,
  /// expired session, server error.
  Future<VehicleProfile?> lookupVehicle(
    String code, {
    GeoPoint? boardingPoint,
  });

  /// Starts a payment for boarding [vehicle], covering [quantity] passengers.
  ///
  /// One payment buys [quantity] tickets — the group case, where one person
  /// pays for friends or family travelling together. The amount claimed is the
  /// per-person fare times [quantity]; it is a claim, not a price, and the
  /// server re-derives the total and rejects a mismatch.
  ///
  /// [idempotencyKey] MUST be generated by the caller before the first attempt
  /// and reused on every retry of the same purchase (I2). One key covers the
  /// whole group: a retry must replay the entire purchase, never issue a second
  /// batch of tickets for a payment already made.
  Future<PaymentStartResult> startVehiclePayment({
    required VehicleProfile vehicle,
    required Money amount,
    required int quantity,
    required PaymentMethod method,
    required String idempotencyKey,
  });

  /// Re-reads a payment's status. Only `CONFIRMED` counts as paid.
  Future<PaymentStatus> vehiclePaymentStatus(String paymentId);

  /// The tickets issued against a confirmed vehicle payment — one per passenger
  /// in the group.
  ///
  /// Returns an **empty list** while they have not been issued yet, which is a
  /// normal intermediate state rather than an error. The caller polls until it
  /// is non-empty.
  ///
  /// The server may legitimately return fewer tickets than were paid for (a
  /// partial issuance). The caller surfaces that rather than treating it as
  /// success, because a passenger who paid for four and received three has a
  /// dispute, not a completed purchase.
  Future<List<IssuedTicket>> ticketsForVehiclePayment(String paymentId);

  /// Refreshes a ticket so the passenger sees the latest recorded state.
  ///
  /// Optional on the server: a 404 or 405 means the endpoint is not deployed,
  /// which is not a reason to hide the QR.
  Future<IssuedTicket?> refreshTicket(String ticketId);

  /// The full entry/exit ledger for a ticket.
///
/// Ordered oldest-first. Two entries — one entry scan, one exit scan — is the
/// healthy, complete case. More than that means the ticket was re-presented,
/// which is what the server refuses rather than the client.
Future<List<TicketValidationRecord>> ticketValidations(String ticketId);

/// Presents a ticket to a validator for a [kind] scan.
///
/// The passenger app calls this when the vehicle's own device scans the QR, so
/// the passenger sees the same recorded outcome the validator does. Returns the
/// server's verdict rather than a boolean: whether an ALREADY_USED or an EXPIRED
/// reads differently to the person holding the phone, and collapsing them into
/// "invalid" is how a legitimate passenger ends up arguing at a gate.
Future<ValidationOutcome> recordValidation({
  required String ticketId,
  required ValidationKind kind,
  String? tripId,
});
}